apiVersion: apps/v1
kind: Deployment
metadata:
  name: gargantua-shell
  labels:
    app: gargantua-shell
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ $.Values.shell.replicas }}
  selector:
    matchLabels:
      app: gargantua-shell
  template:
    metadata:
      labels:
        app: gargantua-shell
    spec:
      containers:
      - name: gargantua
        image: {{ $.Values.gargantua.image }}
        command:
        - gargantua
        - -alsologtostderr
        - -v=9
        - -shellserver
        - -disablecontrollers
---
apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gargantua-shell
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
      targetPort: 80
---
{{ if $.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: shell
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ $.Values.ingress.hostnames.shell }}
    http:
      paths:
      - backend:
          serviceName: shell
          servicePort: http
{{ if $.Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $.Values.ingress.hostnames.shell }}
{{- if hasKey .Values.ingress.tls.secrets "shell" }}
    secretName: {{ $.Values.ingress.tls.secrets.shell }}
{{- end }}
{{ end }}
{{ end }}
