apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: admin-ui
  template:
    metadata:
      labels:
        component: admin-ui
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/admin-ui/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: admin-ui
          image: {{ $.Values.admin.image }}
          {{ if $.Values.insecure }}
          args:
            - --insecure
          {{ end -}}
          env:
            - name: HF_SERVER
              {{ if $.Values.ingress.enabled }}
              value: {{ $.Values.ingress.hostnames.backend | quote }}
              {{ else }}
              value: gargantua
              {{ end }}
      {{- if $.Values.admin.configMapName }}
          volumeMounts:
            {{ if $.Values.admin.config }}
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
            {{ end }}
      volumes:
        - name: config
          configMap: 
            name: {{ $.Values.admin.configMapName }}
      {{- end }}
