{{ if $.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ $.Values.ingress.hostnames.ui }}
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
{{ if $.Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $.Values.ingress.hostnames.ui }}
{{- if hasKey .Values.ingress.tls.secrets "ui" }}
    secretName: {{ $.Values.ingress.tls.secrets.ui }}
{{- end }}
{{ end }}
{{ end }}
