{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hf-shim-vmc-role
  labels:
    {{- include "hf-ec2-vmcontroller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hf-shim-vmc-cluster-role
  labels:
    {{- include "hf-ec2-vmcontroller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - hobbyfarm.io
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ec2.cattle.io
      - droplet.cattle.io
      - equinix.cattle.io
    resources:
      - instances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ec2.cattle.io
      - droplet.cattle.io
      - equinix.cattle.io
    resources:
      - instances/status
    verbs:
      - get
  - apiGroups:
      - ec2.cattle.io
      - droplet.cattle.io
      - equinix.cattle.io
    resources:
      - importkeypairs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ec2.cattle.io
      - droplet.cattle.io
      - equinix.cattle.io
    resources:
      - importkeypairs/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hf-shim-vmc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hf-shim-vmc-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-ec2-vmcontroller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hf-shim-vmcontroller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hf-shim-vmc-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-ec2-vmcontroller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}